// <auto-generated></auto-generated>

namespace CSP.HerculesFreight
{
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DETAILS
    {

        private DETAILSFulladdress fulladdressField;

        private DETAILSFromtosection fromtosectionField;

        private DETAILSRow[] rowItemField;

        private DETAILSRateTariff rateTariffField;

        private DETAILSPleaseNote pleaseNoteField;

        /// <remarks/>
        public DETAILSFulladdress fulladdress
        {
            get
            {
                return this.fulladdressField;
            }
            set
            {
                this.fulladdressField = value;
            }
        }

        /// <remarks/>
        public DETAILSFromtosection fromtosection
        {
            get
            {
                return this.fromtosectionField;
            }
            set
            {
                this.fromtosectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Row", IsNullable = false)]
        public DETAILSRow[] RowItem
        {
            get
            {
                return this.rowItemField;
            }
            set
            {
                this.rowItemField = value;
            }
        }

        /// <remarks/>
        public DETAILSRateTariff RateTariff
        {
            get
            {
                return this.rateTariffField;
            }
            set
            {
                this.rateTariffField = value;
            }
        }

        /// <remarks/>
        public DETAILSPleaseNote PleaseNote
        {
            get
            {
                return this.pleaseNoteField;
            }
            set
            {
                this.pleaseNoteField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DETAILSFulladdress
    {

        private string nameField;

        private string addressField;

        private string cityField;

        private string stateField;

        private uint zipField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public uint zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DETAILSFromtosection
    {

        private uint fROMField;

        private uint rateQuoteField;

        private uint toField;

        private string dATEField;

        private byte averageTransitTimeField;

        private string termsField;

        /// <remarks/>
        public uint FROM
        {
            get
            {
                return this.fROMField;
            }
            set
            {
                this.fROMField = value;
            }
        }

        /// <remarks/>
        public uint RateQuote
        {
            get
            {
                return this.rateQuoteField;
            }
            set
            {
                this.rateQuoteField = value;
            }
        }

        /// <remarks/>
        public uint TO
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        public string DATE
        {
            get
            {
                return this.dATEField;
            }
            set
            {
                this.dATEField = value;
            }
        }

        /// <remarks/>
        public byte AverageTransitTime
        {
            get
            {
                return this.averageTransitTimeField;
            }
            set
            {
                this.averageTransitTimeField = value;
            }
        }

        /// <remarks/>
        public string Terms
        {
            get
            {
                return this.termsField;
            }
            set
            {
                this.termsField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DETAILSRow
    {

        private string typeField;

        private string descriptionField;

        private string classField;

        private string weightField;

        private string rateField;

        private decimal chargesField;

        private string hAZMATField;

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <remarks/>
        public string Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        public string Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }

        /// <remarks/>
        public decimal Charges
        {
            get
            {
                return this.chargesField;
            }
            set
            {
                this.chargesField = value;
            }
        }

        /// <remarks/>
        public string HAZMAT
        {
            get
            {
                return this.hAZMATField;
            }
            set
            {
                this.hAZMATField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DETAILSRateTariff
    {

        private uint rateRuleField;

        private string tariffField;

        /// <remarks/>
        public uint RateRule
        {
            get
            {
                return this.rateRuleField;
            }
            set
            {
                this.rateRuleField = value;
            }
        }

        /// <remarks/>
        public string Tariff
        {
            get
            {
                return this.tariffField;
            }
            set
            {
                this.tariffField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DETAILSPleaseNote
    {

        private DETAILSPleaseNoteNotes1 notes1Field;

        private DETAILSPleaseNoteNotes2 notes2Field;

        /// <remarks/>
        public DETAILSPleaseNoteNotes1 notes1
        {
            get
            {
                return this.notes1Field;
            }
            set
            {
                this.notes1Field = value;
            }
        }

        /// <remarks/>
        public DETAILSPleaseNoteNotes2 notes2
        {
            get
            {
                return this.notes2Field;
            }
            set
            {
                this.notes2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DETAILSPleaseNoteNotes1
    {

        private string pField;

        /// <remarks/>
        public string p
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DETAILSPleaseNoteNotes2
    {

        private string pField;

        /// <remarks/>
        public string p
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }
    }
}